config/routes.rb
Rails.application.routes.draw do
  root to:"users#index"
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post

    return unless user.present?

    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id

    return unless user.role == 'admin'

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_save :increment_comments_counter

  def increment_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :increment_likes_counter

  def increment_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }

  after_save :increment_posts_counter

  def increment_posts_counter
    author.increment!(:posts_counter)
  end

  def recent_comment_counter
    comments.order(created_at: :desc).limit(5)
  end

  def all_comments
    comments.order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, class_name: 'Post', foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def recent_post_counter
    posts.order(created_at: :desc).limit(3)
  end

  ROLES = %w[admin].freeze

  ROLES.each do |exact_role|
    define_method "#{exact_role}?" do
      role == exact_role
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    respond_to do |format|
      format.html { render :new, locals: { comment: @comment } }
    end
  end

  def create
    @user = User.find(params[:user_id])
    post = Post.find(params[:post_id])
    @comment = @user.comments.new(comments_params)
    @comment.author_id = @user.id
    @comment.post_id = params[:post_id]
    if @comment.save
      flash[:notice] = 'Comment successfully created!'
      redirect_to user_post_path(@user.id, post)
    else
      flash.now[:error] = 'Error: Comment creation not successful'
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find_by!(id: params[:post_id])
    comment = Comment.find_by!(post_id: params[:post_id], id: params[:id])
    comment.destroy
    @post.decrement!(:comments_counter)
    flash[:notice] = 'The comment was deleted'
    redirect_to user_post_path(@user, @post)
  end

  def comments_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @like = Like.new(author: @user, post_id: params[:post_id])

    @like.author_id = @user.id
    @like.post_id = params[:post_id]
    redirect_to user_post_path(@user, @post) if @like.save
  end

  private

  def set_post; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    current_user = User.find(params[:user_id])
    @post = Post.new(post_params)
    @post.author = current_user
    # @post.user_id = current_user.id
    @post.comments_counter = 0
    @post.likes_counter = 0
    if @post.save
      flash[:notice] = 'Post successfully created!'
      redirect_to user_posts_path(current_user)
    else
      flash.now[:error] = 'Error: Error occurred when creating post'
      render :new
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find_by!(id: params[:id], author_id: params[:user_id])
  end

  def destroy
    current_user = User.find(params[:user_id])
    post = Post.find_by!(id: params[:id])
    post.destroy
    current_user.decrement!(:posts_counter)
    flash[:notice] = 'The post was deleted'
    redirect_to user_posts_path(current_user)
  end

  private

  def post_params
    params.require(:new_post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<br />
<h1 class="text-primary mt-16">Add new comments</h1>

<%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, scope: :comment, html: { class: "bg-blue-200 p-4 rounded fields" } do |form| %>
  <div class="mb-4">
    <%= form.label :text, class: "mb-2" %><br>
    <%= form.text_area :text, class: "w-100 border-primary p-2" %>
  </div>
  <div class="login">
    <%= form.submit "Add Comment", class: "btn btn-primary bg-blue-500 text-white p-2 rounded text-center w-100" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body class="body">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_user.html.erb
 <% @users.each do |user| %>
 <div class="users-wrapper flex">
    <div class="img-cont">
      <%= image_tag (user.photo.nil? ? "user.png" : user.photo), :size => "100x100", alt: "user photo" %>
    </div>
    <div class="user-details rounded-2xl">
      <h2><%= link_to user.name, user, class: "link-button"  %></h2>
      <p>Number of posts: <%= user.posts_counter %></p>
    </div>
 </div>
 <%end%>

app/views/posts/index.html.erb
<div class="main-container">
  <div class="users-wrapper flex">
    <div class="img-cont">
      <%= image_tag (@user.photo.nil? ? "user.png" : @user.photo), :size => "100x100", alt: "user photo" %>
    </div>
    <div class="user-details">
      <h2><%= @user.name %></h2>
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>

  <% @posts.each do |post| %>
    <div class="posts-enclosure">
      <div class="users-post">
        <h2><%= link_to post.title, user_post_path(@user.id, post.id), class: "link-button" %></h2>
        <p><%= post.text %></p>
        <h4>Comments: <%=post.comments_counter %>, Likes: <%= post.likes_counter %></h4>
        <% if can? :destroy, post %>
          <%=button_to "Delete Post", user_post_path(@user, post),  class: "btn btn-primary bg-blue-500 text-white p-2 rounded text-center", method: :delete %>
        <% end %>
        <br />
        <%= form_with url: "/users/#{@user.id}/posts/#{post.id}/likes", model: Like do |form| %>
          <%= form.submit "Like Post", class: "btn btn-primary bg-blue-500 text-white p-2 rounded text-center" %>
        <% end %>
      </div>
      <div class="comments-cont">
        <% if post.recent_comment_counter.count.zero? %>
          <p>No comments on this post yet</p>
        <% else %>
        <% post.recent_comment_counter.each do |comment| %>
          <p><%= comment.author.name %>: <%= comment.text %></p>
        <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
  <br />
  <button class="w-100"> 
    <%= link_to 'Add new Post', user_posts_path(@user) + '/new', class: "btn btn-primary bg-blue-500 text-white p-2 rounded text-center w-100" %>
  </button>
</div>
 

app/views/posts/new.html.erb
<br />
<h1 class="text-primary mt-16">Add A New Post</h1>
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :new_post, class: "fields" do |form| %>
  <div class="bg-blue-200 p-4 rounded mb-4">
    <div class="mb-4">
      <%= form.label :title, class: "font-weight-bold" %><br>
      <%= form.text_field :title, class: "bg-white border border-primary p-2 rounded w-100" %>
    </div>

    <div class="mb-4">
      <%= form.label :text, class: "font-weight-bold" %><br>
      <%= form.text_area :text, rows: 9, class: "bg-white border border-primary p-4 rounded w-100" %>
    </div>
    <div class="login">
      <%= form.submit "Click to Add Post", class: "btn btn-primary bg-blue-500 text-white p-2 rounded text-center w-100" %>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="main-container">
  <div class="post-container">
    <h2><%= @post.title %> by <%= @post.author.name %></h2>
    <h6>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></h6>
    <p class="post-text"><%= @post.text %></p>
  </div>

  <div class="comments-cont">
    <% if @post.all_comments.count.zero? %>
    <p>Post has no comments yet</p>
    <%else%>
    <% @post.all_comments.each do |comment| %>
      <p><%= comment.author.name %>: <%= comment.text %></p>
      <% if can? :destroy, comment %>
        <%= button_to 'Delete Comment', user_post_comment_path(@user, @post, comment.id), class: "btn btn-primary bg-blue-500 text-white p-2 rounded text-center", method: :delete %>
      <% end %> 
    <% end %>
    <% end %>
  </div>
  <br />
  <button class="w-100"> 
    <%= link_to 'Add new Comment', user_post_path(@user, @post.id) + '/comments/new', class: "btn btn-primary bg-blue-500 text-white p-2 rounded text-center w-100" %>
  </button>
</div>

app/views/users/index.html.erb
<div class="container d-flex flex-column">
 <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "link-button reload" %>
   <%= render partial: 'partials/user' %>
</div>

app/views/users/show.html.erb
<div class="main-container flex">
  <div class="users-wrapper flex">
      <div class="img-cont">
        <%= image_tag (@user.photo.nil? ? "user.png" : @user.photo), :size => "100x100", alt: "user photo" %>
      </div>
      <div class="user-details">
        <h2><%= @user.name %></h2>
        <p>Number of posts: <%= @user.posts_counter %></p>
      </div>
  </div>

  <div class="user-bio">
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
  </div>

  <div class="user-posts">
    <% if @user.recent_post_counter.count.zero? %>
    <p><%= @user.name %> has no posts yet</p>
    <% else %>
    <% @user.recent_post_counter.each do |post| %>
    <%= link_to user_post_path(@user.id, post.id), {:class => "link-button"} do%>
      <div class="users-post">
        <h2><%= post.title %></h2>
        <p><%= post.text %></p>
        <h4>Comments: <%=post.comments_counter %>, Likes: <%= post.likes_counter %></h4>
      </div>
      <% end %>
      <% end %>
      <% end %>

      <button>
        <%= link_to "See all posts", user_posts_path(@user), class: "btn btn-primary bg-blue-500 text-white p-2 rounded text-center w-100" %>
      </button>
  <div>
 </div>